name: Build and Push Docker Images

on:
    push:
        branches:
            - main

env:
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
    build-and-push:
        name: Build and Push Docker Images
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Build
              run: |
                  docker compose --env-file=/github/workspace/${{ secrets.DOCKER_ENV_FILE }} build
            - name: Push Auth Image
              env:
                  DOCKER_BUILDKIT: 1
              run: |
                  docker tag mauagendar-auth luisgmunhoz/mauagendar-auth
                  echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
                  docker push luisgmunhoz/mauagendar-auth

            - name: Push Calendar Image
              env:
                  DOCKER_BUILDKIT: 1
              run: |
                  docker tag mauagendar-calendar luisgmunhoz/mauagendar-calendar
                  echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
                  docker push luisgmunhoz/mauagendar-calendar
